### PR TITLE
migrate flask-babelex to Flask-Babel

### PR DESCRIPTION
**Pull request by hjlarry**
the [flask-babelex](https://github.com/mrjoes/flask-babelex/) is archived by the owner
and in the repo page, suggest us migrate to the new Flask-Babel

### CODE REVIEW

**Comment by BenjaminLECHA** [comment]
I love the suggestion, but it would be necessary to do modification inside all the exemple (requirements and import), readme, setup and requirements-dev

**Comment by martincpt** [comment]
+1 for this!

**Comment by LeXofLeviafan** [comment]
The latest release [appears to support both libraries at the moment](https://github.com/flask-admin/flask-admin/blob/v1.6.1/flask_admin/babel.py#L2-L5) (with preference to `flask-babelex`)

**Comment by samuelhwilliams** [comment]
Closing to move new discussion here: https://github.com/pallets-eco/flask-admin/issues/2447

**Pull request closed without merging**
