### PR TITLE
#Improve | Prettify .gitignore and add a few more environments

### PR DESCRIPTION
**Pull request by princerb**
I think this can make some arrangements? Also I just added a few more virtual environment ignores .

### CODE REVIEW

**Review by samuelhwilliams — COMMENTED** [review]
Is this auto generated from something (if so, what)?Is it a change that we need for some reason (does it cause you a problem that can't be solved with your own global `.gitignore` file)? I'm not super inclined to merge PRs that just shuffle things around without a clear useful reason.

**Comment by princerb** [comment]
No auto-generate, just got the items seperating and ordering by category for the future.

**Comment by hasansezertasan** [comment]
> No auto-generate, just got the items seperating and ordering by category for the future.

I usually use GitHub auto-generated `.gitignore` file as a starting point and add additional stuff underneath.

https://github.com/hasansezertasan/not-just-a-todo-app/blob/143cfaef6ead92fb5354363bca425940b33698d5/.gitignore#L161-L175

**Comment by princerb** [comment]
> > No auto-generate, just got the items seperating and ordering by category for the future.
> 
> I usually use GitHub auto-generated `.gitignore` file as a starting point and add additional stuff underneath.
> 
> https://github.com/hasansezertasan/not-just-a-todo-app/blob/143cfaef6ead92fb5354363bca425940b33698d5/.gitignore#L161-L175

Sure, I also use `.gitignore` templates of Python, but in this pull-requests, I just ordered them by categories, like default templates'.

**Pull request closed without merging**
