### PR TITLE
fix for flask-admin not using flask json_encoder

### PR DESCRIPTION
**Pull request by oleksandr-l5**

### CODE REVIEW

**Comment by caffeinatedMike** [comment]
Can you explain the reasoning for this change? An empty PR description will in most cases lead to the PR being vetoed.

**Comment by oleksandr-l5** [comment]
for example, I added a ObjectId or Decimal or LazyString type field to the flask json_encoder and I want it to be correctly serialized in the whole project

**Comment by oleksandr-l5** [comment]
With this code I can use custom jsonencoder in whole app by setting jsonencoder in flask app. Do you need some example?

**Comment by samuelhwilliams** [comment]
Closing this due to the age and the lack of clarity around purpose. If this is still an issue you are welcome to open another PR with more details, test cases, etc.

**Pull request closed without merging**
