### PR TITLE
Dependencies via pip extras

### PR DESCRIPTION
**Pull request by samuelhwilliams**
We previously haven't ever had a single place that clearly says what dependencies Flask-Admin expects for the 'optional' features, and what versions of those dependencies are required.

This PR pulls all of this information into `pyproject.toml` and exposes them as extras.

All of the examples have been updated to install using these extras, which simplifies their requirements files.

## **OLD NEWS**
<details><summary><strong>temporarily disabled `constrain_package_deps`<strong></summary>
<p>
**This is now outdated and a recent commit on the PR has re-enabled this by adding a constraints file.**

The controversial change here is that, now, in our 'standard' test runs, we can't get the `flask-mongoengine` tests to pass because that dependency is very out of date and doesn't support the latest versions of Flask that we support. We may need to consider deprecating/removing `flask-mongoengine` altogether, but I'm leaving that decision to be had on this thread: https://github.com/pallets-eco/flask-admin/issues/2466. I've added a 'snowflake' tox env for flask-mongoengine that pins required (old) versions of flask/werkzeug/sqlalchemy in the mean time and disabled flask-mongoengine tests in the main suites.

I've also had to disable `constrain_package_deps` in `tox.ini` as we're getting a dependency conflict from google's appengine-python-standard, which requires urllib3<2. I've raised an issue on this here: https://github.com/GoogleCloudPlatform/appengine-python-standard/issues/121

```
The conflict is caused by:
    appengine-python-standard 1.1.6 depends on urllib3<2 and >=1.26.2
    appengine-python-standard 1.1.5 depends on urllib3<2 and >=1.26.2
    appengine-python-standard 1.1.4 depends on urllib3<2 and >=1.26.2
    appengine-python-standard 1.1.3 depends on urllib3<2 and >=1.26.2
    appengine-python-standard 1.1.2 depends on urllib3<2 and >=1.26.2
    appengine-python-standard 1.1.1 depends on urllib3<2 and >=1.26.2
    appengine-python-standard 1.1.0 depends on urllib3<2 and >=1.26.2
    appengine-python-standard 1.0.0 depends on urllib3<2 and >=1.26.2
    appengine-python-standard 0.3.1 depends on urllib3<2 and >=1.26.2
    appengine-python-standard 0.3.0 depends on urllib3<2 and >=1.26.2
    appengine-python-standard 0.2.4 depends on urllib3<2 and >=1.26.2
    appengine-python-standard 0.2.3 depends on urllib3<2 and >=1.26.2
    appengine-python-standard 0.2.2 depends on urllib3<2 and >=1.26.2
    appengine-python-standard 0.2.1 depends on urllib3<2 and >=1.26.2
    appengine-python-standard 0.2.0 depends on urllib3<2 and >=1.26.2
    appengine-python-standard 0.1.1 depends on urllib3<2 and >=1.26.2
    appengine-python-standard 0.1.0 depends on urllib3<2 and >=1.26.2
    The user requested (constraint) urllib3==2.2.2

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict

ERROR: Cannot install appengine-python-standard==0.1.0, appengine-python-standard==0.1.1, appengine-python-standard==0.2.0, appengine-python-standard==0.2.1, appengine-python-standard==0.2.2, appengine-python-standard==0.2.3, appengine-python-standard==0.2.4, appengine-python-standard==0.3.0, appengine-python-standard==0.3.1, appengine-python-standard==1.0.0, appengine-python-standard==1.1.0, appengine-python-standard==1.1.1, appengine-python-standard==1.1.2, appengine-python-standard==1.1.3, appengine-python-standard==1.1.4, appengine-python-standard==1.1.5 and appengine-python-standard==1.1.6 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```
</p>
</details> 

## Documentation update
image

---

fixes: https://github.com/pallets-eco/flask-admin/issues/2452

### CODE REVIEW

**Comment by hasansezertasan** [comment]
I'm pleased that you renamed some dependencies. I hated the `db-` prefix...

**Comment by samuelhwilliams** [comment]
> I'm pleased that you renamed some dependencies. I hated the db- prefix... 👏

So did I, about 5 minutes after doing it 😂  It does feel better without.

I think re: using hatch - there's probably quite a few options at the moment (poetry, hatch, rye, etc) - and I think as part of the pallets ecosystem we probably need to stay in lock-step with what the rest of the projects are doing generally. So I'm not super keen to visit that yet, but maybe worth kicking off a discussion in the discord?

**Comment by hasansezertasan** [comment]
> So did I, about 5 minutes after doing it 😂 It does feel better without.

😆

> I think re: using hatch - there's probably quite a few options at the moment (poetry, hatch, rye, etc)

Did we ever use Hatch with Flask Admin before? Poetry is another great option but it doesn't support independent environments...

> and I think as part of the pallets ecosystem we probably need to stay in lock-step with what the rest of the projects are doing generally. So I'm not super keen to visit that yet, but maybe worth kicking off a discussion in the discord?

Ehem... let's do that 😄.

**Comment by samuelhwilliams** [comment]
@cjmayo I believe so, yes - following what flask-sqlalchemy does:

https://github.com/pallets-eco/flask-sqlalchemy/blob/main/tox.ini#L15-L17
https://github.com/pallets-eco/flask-sqlalchemy/blob/main/requirements-skip/tests-min.in

**Pull request merged**
