### PR TITLE
Docs: adding a favicon

### PR DESCRIPTION
**Pull request by ElLorans**
Added section to the docs; changed example to use redirect in place of send_file.

### CODE REVIEW

**Review by samuelhwilliams — APPROVED** [review]
🙏

**Comment by samuelhwilliams** [comment]
Please you could fix the styling issue, then happy to merge 👍

**Comment by samuelhwilliams** [comment]
p.s. I would recommend installing `pre-commit` and then you can either:

* Install the hooks with `pre-commit install --install-hooks` so that they run automatically before every commit
* Or do a one-off run with `pre-commit run --all-files`

**Comment by ElLorans** [comment]
Opened https://github.com/pallets-eco/flask-admin/pull/2563 to have a clean commit history

**Pull request closed without merging**
